apiVersion: v1
kind: Service
metadata:
  name: netology-svc-wait
  namespace: netology  
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: to-wait
      