apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-viewer
  namespace: default
subjects:
  - kind: User
    name: ALEX
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: pod-viewer
  apiGroup: rbac.authorization.k8s.io