apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-label
  template:
    metadata:
      labels:
        app: dep-label
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"] 
        args: 
          - while :; do 
            echo $(date) | tee -a /output/file; 
            sleep 5;
            done        
        volumeMounts:
        - name: vol
          mountPath: /output
      - name: multitool
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c"]
        args: ["tail -f /input/file"]
        volumeMounts:
        - name: vol
          mountPath: /input
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: test-pvc