apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange
  namespace: netology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-lable
  template:
    metadata:
      labels:
        app: data-exchange-lable
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"] 
        args: ["echo $(date) > /output/file; sleep 3600"] 
        volumeMounts:
        - name: vol
          mountPath: /output
      - name: multitool
        image: wbitt/network-multitool
        ports:
          - containerPort: 80
        command: ["/bin/sh", "-c"]
        args: ["tail -f /input/file"] 
        volumeMounts:
        - name: vol
          mountPath: /input
      volumes:
      - name: vol
        emptyDir: {} 