apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-storage
spec:
  capacity:
    storage: 1.1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: test-sc
  hostPath:
    path: /tmp/test-storage